diyblog/blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


urlpatterns = [
    path('', views.index, name='index'),
    url(r'^blogs/$', views.BlogListView.as_view(), name='blogs'),
    url(r'^(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='blog-detail'),
    url(r'^(?P<pk>\d+)/create$', views.CommentCreate.as_view(), name='comment_create'),
    url(r'^bloggers/$', views.BloggerListView.as_view(), name='bloggers'),
    url(r'^bloggers/(?P<pk>\d+)$', views.BloggerDetailView.as_view(), name='blogger-detail'),
]

diyblog/diyblog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf.urls import url

from django.conf import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

diyblog/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Blog(models.Model):
    title = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('Blogger', on_delete=models.SET_NULL, null=True)
    description = models.TextField(
        max_length=10000,
        help_text='Enter a description of blog'
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])

    class Meta:
        ordering = ['-created']


class Blogger(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bio = models.TextField(
        max_length=10000,
        help_text='Enter a bio of blogger'
    )

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('blogger-detail', args=[str(self.id)])

    class Meta:
        ordering = ['user']


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    description = models.TextField(
        max_length=10000,
        help_text='Enter comment about blog here.'
    )

    def __str__(self):
        len_title = 75
        if len(self.description) > len_title:
            titlestring = self.description[:len_title] + '...'
        else:
            titlestring = self.description
        return titlestring

    class Meta:
        ordering = ['created']

diyblog/blog/views.py
from django.shortcuts import render
from .models import Blog, Blogger, Comment
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy


def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_blogs = Blog.objects.all().count()
    num_bloggers = Blogger.objects.all().count()
    num_comments = Comment.objects.all().count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'index.html',
        context={
            'num_blogs': num_blogs,
            'num_bloggers': num_bloggers,
            'num_comments': num_comments,
            'num_visits': num_visits,
        },
    )


class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5


class BloggerListView(generic.ListView):
    model = Blogger
    paginate_by = 5


class BlogDetailView(generic.DetailView):
    model = Blog


class BloggerDetailView(generic.DetailView):
    model = Blogger


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ('description',)

    def get_success_url(self):
        return reverse_lazy('blog-detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super(CommentCreate, self).get_context_data(**kwargs)
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])
        context['pk'] = self.kwargs['pk']
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        return super(CommentCreate, self).form_valid(form)

diyblog/blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  {% block title %}<title>DIY Blog</title>{% endblock %}
</head>

<body>
  <div class="container-fluid mt-3 mt-md-5">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'blogs' %}">All blogs</a></li>
          <li><a href="{% url 'bloggers' %}">All bloggers</a></li>
          <div class="mt-3">
            {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
          </div>
        </ul>
        {% endblock %}
      </div>
      <div class="col-sm-10">
        {% block content %}{% endblock %}

        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
          </span>
        </div>
        {% endif %}
        {% endblock %}
      </div>
    </div>
  </div>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

diyblog/blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>{{ blog.title }}</h1>
<p><strong>Post date</strong> {{ blog.created|date:"M. d, Y" }}</p>
<p><strong>Author:</strong> {{ blog.author }}</p>
<p><strong>Description:</strong></p>
<p>{{ blog.description }}</p>

<div class="ml-2 mt-2">
  <h5>Comments</h5>
  <hr>

  {% for comment in blog.comment_set.all %}
    <p>{{ comment.author }} ({{ comment.created }}) - {{ comment.description }}</p>
    <hr>
  {% endfor %}
  {% if user.is_authenticated %}
    <a href="{% url 'comment_create' blog.id %}">Add a new comment</a>
  {% else %}
    <a href="{% url 'login' %}">Login</a> to add a new comment
  {% endif %}
</div>
{% endblock %}

diyblog/blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>All blogs</h1>

{% if blog_list %}
<ul>

  {% for blog in blog_list %}
  <li>
    <a href="{% url 'blog-detail' blog.id %}">{{ blog.title }}</a> ({{ blog.created|date:"M. d, Y" }}) - <a href="{{ blog.author.get_absolute_url }}">{{ blog.author }}</a>
  </li>
  {% endfor %}

</ul>
{% else %}
<p>There are no blogs.</p>
{% endif %}
{% endblock %}

diyblog/blog/templates/blog/blogger_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Blogger: {{ blogger.user.username }}</h1>
<h5>Bio</h5>
<p>{{ blogger.bio }}</p>

<div class="ml-2 mt-2">
  <h5>Blogs list</h5>
  <ul>
    {% for blog in blogger.blog_set.all %}
    <li>
      <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{ blog.created|date:"M. d, Y" }})
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

diyblog/blog/templates/blog/blogger_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>All bloggers</h1>

{% if blogger_list %}
<ul>

  {% for blogger in blogger_list %}
  <li>
    <a href="{% url 'blogger-detail' blogger.id %}">{{ blogger.user.username }}</a>
  </li>
  {% endfor %}

</ul>
{% else %}
<p>There are no bloggers.</p>
{% endif %}
{% endblock %}

diyblog/blog/templates/blog/comment_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
  {% csrf_token %}
  <p>Post your comment for: <a href="{% url 'blog-detail' pk %}">{{ blog.title }}</a></p>
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />

</form>
{% endblock %}

diyblog/blog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}<title>Blog</title>{% endblock %}

{% block content %}
<h1>DIY Blog Home</h1>

<p>Welcome to <em>DIY Blog</em>.</p>

<h2>Dynamic content</h2>

<p>The blog has the following record counts:</p>
<ul>
  <li><strong>Blogs:</strong> {{ num_blogs }}</li>
  <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
  <li><strong>Comments:</strong> {{ num_comments }}</li>
</ul>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}